### ISSUE TITLE
Build failure with --enable-debug

### ISSUE THREAD

**Issue by speed47** [speed47/qpxtool#6]
```
src/abstractpreview.cpp: In member function 'virtual void AbstractPreview::printPages(QPrinter*)':
src/abstractpreview.cpp:1424:85: error: 'struct timespec' has no member named 'tv_usec'; did you mean 'tv_sec'?
 1424 |   qDebug() << "Pages time: " << QString(" %1 s").arg(tpe.tv_sec - tpb.tv_sec + (tpe.tv_usec - tpb.tv_usec)/1000000.0,0,'f',4);
      |                                                                                     ^~~~~~~
      |                                                                                     tv_sec
src/abstractpreview.cpp:1424:99: error: 'struct timespec' has no member named 'tv_usec'; did you mean 'tv_sec'?
 1424 |   qDebug() << "Pages time: " << QString(" %1 s").arg(tpe.tv_sec - tpb.tv_sec + (tpe.tv_usec - tpb.tv_usec)/1000000.0,0,'f',4);
      |                                                                                                   ^~~~~~~
      |                                                                                                   tv_sec
```

Problem introduced in d1d0afc35aacf294ed358a1b40d7a206cf355578
